### ISSUE TITLE
What is SwitchCMD

### ISSUE THREAD

**Issue by strunkie30** [seriousme/node-switch#1]
Its unclear what SwitchCMD Means. This directory is empty on my RPi.
Your scripts is running in the following directory:
/nodejs/lights/node_modules/node-switch/

What is switchCMD

**Comment by seriousme** [comment]
a little late answer, sorry for that.

switchCMD is the kaku binary
Its basically the executable that sends the signals to the GPIO of the raspberryPi to control the 433Mhz transmitter
